//! Adobe glyph-name → Unicode for the names that appear in /Differences
//! arrays of ordinary text fonts.

const NAMES: &[(&str, char)] = &[
    ("space", ' '),
    ("exclam", '!'),
    ("quotedbl", '"'),
    ("numbersign", '#'),
    ("dollar", '$'),
    ("percent", '%'),
    ("ampersand", '&'),
    ("quotesingle", '\''),
    ("parenleft", '('),
    ("parenright", ')'),
    ("asterisk", '*'),
    ("plus", '+'),
    ("comma", ','),
    ("hyphen", '-'),
    ("minus", '\u{2212}'),
    ("period", '.'),
    ("slash", '/'),
    ("zero", '0'),
    ("one", '1'),
    ("two", '2'),
    ("three", '3'),
    ("four", '4'),
    ("five", '5'),
    ("six", '6'),
    ("seven", '7'),
    ("eight", '8'),
    ("nine", '9'),
    ("colon", ':'),
    ("semicolon", ';'),
    ("less", '<'),
    ("equal", '='),
    ("greater", '>'),
    ("question", '?'),
    ("at", '@'),
    ("bracketleft", '['),
    ("backslash", '\\'),
    ("bracketright", ']'),
    ("asciicircum", '^'),
    ("underscore", '_'),
    ("grave", '`'),
    ("braceleft", '{'),
    ("bar", '|'),
    ("braceright", '}'),
    ("asciitilde", '~'),
    ("bullet", '\u{2022}'),
    ("endash", '\u{2013}'),
    ("emdash", '\u{2014}'),
    ("quoteleft", '\u{2018}'),
    ("quoteright", '\u{2019}'),
    ("quotedblleft", '\u{201C}'),
    ("quotedblright", '\u{201D}'),
    ("quotesinglbase", '\u{201A}'),
    ("quotedblbase", '\u{201E}'),
    ("ellipsis", '\u{2026}'),
    ("dagger", '\u{2020}'),
    ("daggerdbl", '\u{2021}'),
    ("perthousand", '\u{2030}'),
    ("guilsinglleft", '\u{2039}'),
    ("guilsinglright", '\u{203A}'),
    ("guillemotleft", '\u{AB}'),
    ("guillemotright", '\u{BB}'),
    ("trademark", '\u{2122}'),
    ("copyright", '\u{A9}'),
    ("registered", '\u{AE}'),
    ("degree", '\u{B0}'),
    ("plusminus", '\u{B1}'),
    ("multiply", '\u{D7}'),
    ("divide", '\u{F7}'),
    ("section", '\u{A7}'),
    ("paragraph", '\u{B6}'),
    ("periodcentered", '\u{B7}'),
    ("nbspace", '\u{A0}'),
    ("nonbreakingspace", '\u{A0}'),
    ("sfthyphen", '\u{AD}'),
    ("softhyphen", '\u{AD}'),
    ("fi", '\u{FB01}'),
    ("fl", '\u{FB02}'),
    ("ff", '\u{FB00}'),
    ("ffi", '\u{FB03}'),
    ("ffl", '\u{FB04}'),
    ("Euro", '\u{20AC}'),
    ("sterling", '\u{A3}'),
    ("yen", '\u{A5}'),
    ("cent", '\u{A2}'),
    ("currency", '\u{A4}'),
    ("florin", '\u{192}'),
    ("fraction", '\u{2044}'),
    ("arrowright", '\u{2192}'),
    ("arrowleft", '\u{2190}'),
    ("Agrave", '\u{C0}'),
    ("Aacute", '\u{C1}'),
    ("Acircumflex", '\u{C2}'),
    ("Atilde", '\u{C3}'),
    ("Adieresis", '\u{C4}'),
    ("Aring", '\u{C5}'),
    ("AE", '\u{C6}'),
    ("Ccedilla", '\u{C7}'),
    ("Egrave", '\u{C8}'),
    ("Eacute", '\u{C9}'),
    ("Ecircumflex", '\u{CA}'),
    ("Edieresis", '\u{CB}'),
    ("Igrave", '\u{CC}'),
    ("Iacute", '\u{CD}'),
    ("Icircumflex", '\u{CE}'),
    ("Idieresis", '\u{CF}'),
    ("Ntilde", '\u{D1}'),
    ("Ograve", '\u{D2}'),
    ("Oacute", '\u{D3}'),
    ("Ocircumflex", '\u{D4}'),
    ("Otilde", '\u{D5}'),
    ("Odieresis", '\u{D6}'),
    ("Oslash", '\u{D8}'),
    ("Ugrave", '\u{D9}'),
    ("Uacute", '\u{DA}'),
    ("Ucircumflex", '\u{DB}'),
    ("Udieresis", '\u{DC}'),
    ("Yacute", '\u{DD}'),
    ("germandbls", '\u{DF}'),
    ("agrave", '\u{E0}'),
    ("aacute", '\u{E1}'),
    ("acircumflex", '\u{E2}'),
    ("atilde", '\u{E3}'),
    ("adieresis", '\u{E4}'),
    ("aring", '\u{E5}'),
    ("ae", '\u{E6}'),
    ("ccedilla", '\u{E7}'),
    ("egrave", '\u{E8}'),
    ("eacute", '\u{E9}'),
    ("ecircumflex", '\u{EA}'),
    ("edieresis", '\u{EB}'),
    ("igrave", '\u{EC}'),
    ("iacute", '\u{ED}'),
    ("icircumflex", '\u{EE}'),
    ("idieresis", '\u{EF}'),
    ("ntilde", '\u{F1}'),
    ("ograve", '\u{F2}'),
    ("oacute", '\u{F3}'),
    ("ocircumflex", '\u{F4}'),
    ("otilde", '\u{F5}'),
    ("odieresis", '\u{F6}'),
    ("oslash", '\u{F8}'),
    ("ugrave", '\u{F9}'),
    ("uacute", '\u{FA}'),
    ("ucircumflex", '\u{FB}'),
    ("udieresis", '\u{FC}'),
    ("yacute", '\u{FD}'),
    ("ydieresis", '\u{FF}'),
    ("exclamdown", '\u{A1}'),
    ("questiondown", '\u{BF}'),
    ("ordfeminine", '\u{AA}'),
    ("ordmasculine", '\u{BA}'),
    ("logicalnot", '\u{AC}'),
    ("mu", '\u{B5}'),
    ("onesuperior", '\u{B9}'),
    ("twosuperior", '\u{B2}'),
    ("threesuperior", '\u{B3}'),
    ("onehalf", '\u{BD}'),
    ("onequarter", '\u{BC}'),
    ("threequarters", '\u{BE}'),
    ("brokenbar", '\u{A6}'),
    ("Eth", '\u{D0}'),
    ("eth", '\u{F0}'),
    ("Thorn", '\u{DE}'),
    ("thorn", '\u{FE}'),
    ("OE", '\u{152}'),
    ("oe", '\u{153}'),
    ("Scaron", '\u{160}'),
    ("scaron", '\u{161}'),
    ("Zcaron", '\u{17D}'),
    ("zcaron", '\u{17E}'),
    ("Ydieresis", '\u{178}'),
    ("dotlessi", '\u{131}'),
    ("Lslash", '\u{141}'),
    ("lslash", '\u{142}'),
    ("acute", '\u{B4}'),
    ("circumflex", '\u{2C6}'),
    ("tilde", '\u{2DC}'),
    ("macron", '\u{AF}'),
    ("breve", '\u{2D8}'),
    ("dotaccent", '\u{2D9}'),
    ("dieresis", '\u{A8}'),
    ("ring", '\u{2DA}'),
    ("cedilla", '\u{B8}'),
    ("hungarumlaut", '\u{2DD}'),
    ("ogonek", '\u{2DB}'),
    ("caron", '\u{2C7}'),
];

pub fn name_to_unicode(name: &str) -> Option<String> {
    if name == ".notdef" {
        return None;
    }
    let base = name.split('.').next().unwrap_or(name);
    if base.chars().count() == 1 {
        return Some(base.to_string());
    }
    if let Some(&(_, c)) = NAMES.iter().find(|(n, _)| *n == base) {
        return Some(c.to_string());
    }
    if let Some(hex) = base.strip_prefix("uni")
        && hex.len() >= 4
        && hex.len() % 4 == 0
    {
        let units: Vec<u16> = (0..hex.len())
            .step_by(4)
            .filter_map(|i| u16::from_str_radix(&hex[i..i + 4], 16).ok())
            .collect();
        return Some(String::from_utf16_lossy(&units));
    }
    if let Some(hex) = base.strip_prefix('u')
        && (4..=6).contains(&hex.len())
        && let Some(c) = u32::from_str_radix(hex, 16).ok().and_then(char::from_u32)
    {
        return Some(c.to_string());
    }
    None
}
